FROM lukemathwalker/cargo-chef:latest-rust-1.93.1 AS chef
WORKDIR /app

FROM chef AS planner
# Only copy Cargo manifests and lock file
COPY backend/Cargo.toml backend/Cargo.lock ./
COPY backend/macros/Cargo.toml ./macros/Cargo.toml
COPY backend/migration/Cargo.toml ./migration/Cargo.toml
COPY backend/openapi-cli/Cargo.toml ./openapi-cli/Cargo.toml
COPY backend/rust-toolchain.toml ./rust-toolchain.toml
# Create minimal lib.rs/main.rs stubs required by cargo
RUN mkdir -p src macros/src migration/src openapi-cli/src \
    && touch src/lib.rs src/main.rs macros/src/lib.rs migration/src/lib.rs openapi-cli/src/main.rs
RUN cargo chef prepare --recipe-path recipe.json --bin hack4krak-backend

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
COPY --from=planner /app/openapi-cli/ openapi-cli/
COPY backend .
RUN cargo build --release --bin hack4krak-backend

# We do not need the Rust toolchain to run the binary!
FROM debian:trixie-slim AS runtime
WORKDIR /app
RUN apt-get update && apt-get install -y libssl3 ca-certificates git

# Download TasksTemplate or other tasks repository
ARG GIT_USER=Hack4Krak
ARG GIT_REPO=TasksTemplate
ARG BRANCH=master
# Pass --build-arg CACHEBUST=$(date +%s) to invalidate cache when tasks repo updates
ARG CACHEBUST=0

RUN --mount=type=secret,id=GIT_ACCESS_TOKEN,env=GIT_ACCESS_TOKEN \
  git clone -b $BRANCH "https://${GIT_USER}:${GIT_ACCESS_TOKEN}@github.com/${GIT_USER}/${GIT_REPO}.git" TasksRepo/

ENV TASKS_BASE_PATH=TasksRepo/

COPY --from=builder /app/target/release/hack4krak-backend /usr/local/bin
ENTRYPOINT ["/usr/local/bin/hack4krak-backend"]
